const { chromium } = require('playwright');
const assert = require('node:assert/strict');

(async () => {
  const browser = await chromium.launch({headless:true});
  const page = await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(process.env.TEST_URL || 'http://127.0.0.1:8080', {waitUntil:'networkidle'});
  assert.equal(await page.locator('.product').count(),6);
  await page.getByRole('button',{name:'Para empresas',exact:true}).click();
  assert.equal(await page.locator('.product').count(),5);
  await page.getByRole('button',{name:'Para ti',exact:true}).click();
  assert.equal(await page.locator('.product').count(),5);
  await page.getByRole('button',{name:'Todo el software',exact:true}).click();
  await page.locator('#search').fill('proteccion');
  assert.equal(await page.locator('.product').count(),1);
  await page.locator('#search').fill('zz-no-product');
  assert.equal(await page.locator('#empty').isVisible(),true);
  await page.locator('#reset').click();
  await page.locator('#category').selectOption('Diseño');
  assert.equal(await page.locator('.product').count(),1);
  await page.locator('#category').selectOption('all');
  await page.locator('[data-detail="creative"]').click();
  await page.locator('#add-selection').click();
  assert.equal(await page.locator('#selection-count').textContent(),'1');
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#modal').isVisible(),false);
  await page.reload();
  assert.equal(await page.locator('#selection-count').textContent(),'1');
  for(const id of ['creative','office','security']) await page.locator(`[data-compare="${id}"]`).check();
  await page.locator('[data-compare="dev"]').click();
  assert.equal(await page.locator('[data-compare="dev"]').isChecked(),false);
  await page.locator('#compare-open').click();
  assert.equal(await page.locator('thead th').count(),4);
  await page.keyboard.press('Escape');
  await page.locator('#compare-clear').click();
  await page.locator('#business-quote').click();
  await page.locator('[name="needs"]').fill('Probar <script>alert(1)</script> con 5 usuarios.');
  await page.locator('[name="users"]').fill('5');
  await page.getByRole('button',{name:'Generar resumen'}).click();
  assert.ok((await page.locator('.summary-text').textContent()).includes('<script>alert(1)</script>'));
  assert.equal(await page.locator('#modal-body script').count(),0);
  const downloadPromise = page.waitForEvent('download');
  await page.locator('#download-summary').click();
  assert.equal((await downloadPromise).suggestedFilename(),'consulta-aplivanta.txt');
  await page.keyboard.press('Escape');
  await page.locator('#selection-open').click();
  await page.locator('[data-remove="creative"]').click();
  assert.equal(await page.locator('#selection-count').textContent(),'0');
  await page.keyboard.press('Escape');
  await page.locator('#sort').selectOption('name');
  assert.equal(await page.locator('.product h3').first().textContent(),'Gestión de negocio');
  await page.locator('#sort').selectOption('featured');
  await page.reload({waitUntil:'networkidle'});
  await page.evaluate(()=>{document.activeElement.blur();window.scrollTo(0,0);});
  await page.screenshot({path:'/tmp/aplivanta-desktop.png',fullPage:true});
  for(const width of [390,320,768]){
    await page.setViewportSize({width,height:844});
    await page.evaluate(()=>window.scrollTo(0,0));
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`Overflow at ${width}`);
    await page.locator('#menu-toggle').click();
    assert.equal(await page.locator('#menu-toggle').getAttribute('aria-expanded'),'true');
    await page.locator('#navigation a').first().click();
    assert.equal(await page.locator('#menu-toggle').getAttribute('aria-expanded'),'false');
    if(width===390){ await page.evaluate(()=>{document.activeElement.blur();window.scrollTo(0,0);}); await page.screenshot({path:'/tmp/aplivanta-mobile.png',fullPage:false}); }
  }
  assert.deepEqual(errors,[]);
  await browser.close();
  console.log('PASS: catalog, audience/category/search/sort, comparison limit, details, persistent selection, removal, safe summary/download, Escape, mobile navigation and overflow at 320/390/768px.');
})().catch(e => {console.error(e);process.exit(1)});
